/* Auto-generated by Tools/thermistor_model/generate_thermistor_model.py.
 * Do not edit manually.
 *
 * Source: Vishay NTC R/T Calculator export for NTCLE350E4103FHB0
 * SHA-256: db3446078e15efcf3cc1d0647a4a580ba8a9a18b0edb9a4c60a819551fa7fa83
 */
#ifndef INC_EXT_DRIVERS_THERMISTOR_MODEL_GENERATED_H_
#define INC_EXT_DRIVERS_THERMISTOR_MODEL_GENERATED_H_

#define THERMISTOR_MODEL_PART_NUMBER            "NTCLE350E4103FHB0"
#define THERMISTOR_MODEL_SOURCE_SHA256           "db3446078e15efcf3cc1d0647a4a580ba8a9a18b0edb9a4c60a819551fa7fa83"
#define THERMISTOR_R25_OHM                      (10000.0f)
#define THERMISTOR_B2585_K                      (3984.0f)
#define THERMISTOR_MODEL_MIN_TEMP_C             (-20.0f)
#define THERMISTOR_MODEL_MAX_TEMP_C             (120.0f)
#define THERMISTOR_MODEL_TABLE_STEP_C            (0.5f)

/* Full Vishay extended Steinhart-Hart inverse: R -> T. */
#define THERMISTOR_SH_A1                        (0.00335401643468052988f)
#define THERMISTOR_SH_B1                        (0.000256523550896126009f)
#define THERMISTOR_SH_C1                        (2.60597012072051983e-06f)
#define THERMISTOR_SH_D1                        (6.32926126487459937e-08f)

/* Full Vishay forward equation: T -> R. */
#define THERMISTOR_FWD_A                        (-14.65719769f)
#define THERMISTOR_FWD_B                        (4798.842f)
#define THERMISTOR_FWD_C                        (-115334.0f)
#define THERMISTOR_FWD_D                        (-3730535.0f)

#endif /* INC_EXT_DRIVERS_THERMISTOR_MODEL_GENERATED_H_ */
