#ifndef ZEPHYR_SYS_UTIL_H_
#define ZEPHYR_SYS_UTIL_H_
#define BIT(n) (1UL << (n))
#define IS_ENABLED(x) (x)
#define BUILD_ASSERT(cond, msg) _Static_assert((cond), msg)
#ifndef CONFIG_AMS_CAP_IMD_ACTOR_LIVE
#define CONFIG_AMS_CAP_IMD_ACTOR_LIVE 1
#ifndef CONFIG_AMS_CAP_IMD_CAPTURE_ADAPTER_PRESENT
#define CONFIG_AMS_CAP_IMD_CAPTURE_ADAPTER_PRESENT 1
#endif
#ifndef CONFIG_AMS_CAP_IMD_PHYSICAL_VALIDATED
#define CONFIG_AMS_CAP_IMD_PHYSICAL_VALIDATED 0
#endif
#endif
#ifndef CONFIG_AMS_IMD_TARGET_VALIDATED
#define CONFIG_AMS_IMD_TARGET_VALIDATED 0
#endif
#endif
