#ifndef ZEPHYR_SYS_UTIL_H_
#define ZEPHYR_SYS_UTIL_H_
#define ARG_UNUSED(x) (void)(x)
#define BUILD_ASSERT(cond, msg) _Static_assert((cond), msg)
#define IS_ENABLED(x) (x)
#define CONFIG_AMS_ADBMS_SPI_PRIVATE_BACKEND 1
#ifndef CONFIG_AMS_Z018_TEMP_VALIDATION
#define CONFIG_AMS_Z018_TEMP_VALIDATION 0
#endif
#ifndef CONFIG_AMS_Z018_AUX2_DIAGNOSTIC
#define CONFIG_AMS_Z018_AUX2_DIAGNOSTIC 0
#endif
#ifndef CONFIG_AMS_Z018_THERM_OW_DIAGNOSTIC
#define CONFIG_AMS_Z018_THERM_OW_DIAGNOSTIC 0
#endif
#ifndef CONFIG_AMS_Z017_CELL_VALIDATION
#define CONFIG_AMS_Z017_CELL_VALIDATION 0
#endif
#ifndef CONFIG_AMS_Z016_LINK_PROBE
#define CONFIG_AMS_Z016_LINK_PROBE 0
#endif
#define CONFIG_AMS_BMS_AUTHORITY 0
#define CONFIG_AMS_BALANCE_AUTHORITY 0
#define CONFIG_SPI 0
#define CONFIG_USE_STM32_LL_SPI 1
#define CONFIG_RESET 1
#define CONFIG_CORTEX_M_SYSTICK_64BIT_CYCLE_COUNTER 1
#define CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER 1
#define CONFIG_PM 0
#endif
