#ifndef FAKE_ZEPHYR_IO_CHANNELS_H_
#define FAKE_ZEPHYR_IO_CHANNELS_H_
#define DT_IO_CHANNELS_CTLR_BY_NAME(node, name) DT_IO_CHANNELS_CTLR_BY_NAME_##name
#define DT_IO_CHANNELS_CTLR_BY_NAME_high 11
#define DT_IO_CHANNELS_CTLR_BY_NAME_low 12
#define DT_IO_CHANNELS_INPUT_BY_NAME(node, name) DT_IO_CHANNELS_INPUT_BY_NAME_##name
#define DT_IO_CHANNELS_INPUT_BY_NAME_high 3
#define DT_IO_CHANNELS_INPUT_BY_NAME_low 10
#endif
